### ISSUE TITLE
Yarn install fails on Typescript patch

### ISSUE THREAD

**Issue by kalvinwang** [ivopr/tamagui-expo#25] opened 2023-05-04 06:43 UTC
On a clean repo, `yarn install` was failing for me with this error:

```➤ YN0013: │ typescript@npm:5.0.4 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ typescript@npm:4.9.5 can't be found in the cache and will be fetched from the remote registry
➤ YN0066: │ typescript@patch:typescript@npm%3A5.0.4#builtin<compat/typescript>::version=5.0.4&hash=8133ad: Cannot apply hunk #1 (set enableInlineHunks for details)
➤ YN0066: │ typescript@patch:typescript@npm%3A4.9.5#builtin<compat/typescript>::version=4.9.5&hash=8133ad: Cannot apply hunk #2 (set enableInlineHunks for details)
➤ YN0000: └ Completed in 42s 973ms
➤ YN0000: Failed with errors in 54s 749ms
```

I was able to fix this by adding the following to my .yarnrc.yml:

```enableGlobalCache: true
yarnPath: .yarn/releases/yarn-3.5.1.cjs
```

(I had already run `yarn set version latest` but that was insufficient)

Just posting this here in case it's helpful for someone else!

**Comment by ivopr** [comment] 2023-05-15 12:45
Well, that's strange. I've tried it and it worked.
Maybe because I use [volta](https://volta.sh) to manage things.
I'll be closing this since I couldn't reproduce and you got it working. In any case, if it occurs again feel free to reopen.

**Closed as completed by ivopr** 2023-05-15 12:45 UTC
